// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PenggunaService.Data;

namespace PenggunaService.Migrations
{
    [DbContext(typeof(PenggunaDbContext))]
    partial class PenggunaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PenggunaService.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<double?>("LatDriver")
                        .HasColumnType("float");

                    b.Property<double>("LatPengguna")
                        .HasColumnType("float");

                    b.Property<double>("LatTujuan")
                        .HasColumnType("float");

                    b.Property<double?>("LongDriver")
                        .HasColumnType("float");

                    b.Property<double>("LongPengguna")
                        .HasColumnType("float");

                    b.Property<double>("LongTujuan")
                        .HasColumnType("float");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("PenggunaId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PenggunaService.Models.Pengguna", b =>
                {
                    b.Property<int>("PenggunaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isLocked")
                        .HasColumnType("bit");

                    b.HasKey("PenggunaId");

                    b.ToTable("Penggunas");
                });

            modelBuilder.Entity("PenggunaService.Models.Price", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("PricePerKm")
                        .HasColumnType("real");

                    b.HasKey("PriceId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("PenggunaService.Models.Saldo", b =>
                {
                    b.Property<int>("SaldoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<float?>("MutasiSaldo")
                        .HasColumnType("real");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<float>("TotalSaldo")
                        .HasColumnType("real");

                    b.HasKey("SaldoId");

                    b.HasIndex("PenggunaId");

                    b.ToTable("Saldos");
                });

            modelBuilder.Entity("PenggunaService.Models.Order", b =>
                {
                    b.HasOne("PenggunaService.Models.Pengguna", "Pengguna")
                        .WithMany("Orders")
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("PenggunaService.Models.Saldo", b =>
                {
                    b.HasOne("PenggunaService.Models.Pengguna", "Pengguna")
                        .WithMany("Saldo")
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("PenggunaService.Models.Pengguna", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Saldo");
                });
#pragma warning restore 612, 618
        }
    }
}
